name: torchrl

channels:
  - pytorch

dependencies:
  - python>=3.5
  - pytorch>=0.4
  - numpy
  - scipy
  - pip
  - pip:
      - pyyaml
      - sphinx
      - gym
      - pandas
      - tensorflow
      - tensorboardX
