name: torchrl

channels:
  - soumith

dependencies:
  - python>=3.5
  - pytorch
  - numpy
  - scipy
  - pip
  - pip:
      - pyyaml
      - sphinx
      - gym
      - pandas
      - tensorflow
      - tensorboardX
